//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExploreTandT
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectedPacakge
    {
        public string Name { get; set; }
        public string Category { get; set; }
        public string Places { get; set; }
        public Nullable<int> Range { get; set; }
        public string TourGuide { get; set; }
        public string Schedule { get; set; }
        public string Vehicle { get; set; }
        public string Hotel { get; set; }
        public string Refreshments { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public string AddedBy { get; set; }
        public int SelectedPacakgeId { get; set; }
        public Nullable<int> checkid { get; set; }
    }
}
