//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExploreTandT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB64Entities : DbContext
    {
        public DB64Entities()
            : base("name=DB64Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeLoan> EmployeeLoans { get; set; }
        public virtual DbSet<Installement> Installements { get; set; }
        public virtual DbSet<Loan> Loans { get; set; }
        public virtual DbSet<Lookup> Lookups { get; set; }
        public virtual DbSet<PolicyAndRule> PolicyAndRules { get; set; }
        public virtual DbSet<RepaymentSchedule> RepaymentSchedules { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<SalaryDeduction> SalaryDeductions { get; set; }
    }
}
