//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExploreTandT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Installement()
        {
            this.EmployeeLoans = new HashSet<EmployeeLoan>();
            this.RepaymentSchedules = new HashSet<RepaymentSchedule>();
            this.SalaryDeductions = new HashSet<SalaryDeduction>();
        }
    
        public int Id { get; set; }
        public int LoanId { get; set; }
        public int InstallementPlan { get; set; }
        public int Amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLoan> EmployeeLoans { get; set; }
        public virtual Loan Loan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepaymentSchedule> RepaymentSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaryDeduction> SalaryDeductions { get; set; }
    }
}
